server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    username: root
    password: 13532612697
    url: jdbc:mysql://localhost:3306/bootdev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driverize
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariC
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
#showSql
logging:
  level:
    com.yyj: debug
